import fs from 'fs/promises';
import path from 'path';
import crypto from 'crypto';

const GOOGLE_AUTH_URL = 'https://accounts.google.com/o/oauth2/v2/auth';
const GOOGLE_TOKEN_URL = 'https://oauth2.googleapis.com/token';
const DRIVE_SCOPE = 'https://www.googleapis.com/auth/drive.readonly';
const TOKEN_FILE = process.env.TRIPPEDD_GOOGLE_TOKEN_FILE || path.join(process.cwd(), '.trippedd', 'google-drive-oauth.json');
type StoredTokens = { access_token?: string; refresh_token?: string; expires_at?: number; scope?: string; token_type?: string };
type PendingAuth = { expiresAt: number; verifier: string };
const pendingStates = new Map<string, PendingAuth>();
let cachedTokens: StoredTokens | null = null;
function clientId() { const value = process.env.GOOGLE_CLIENT_ID || process.env.VITE_GOOGLE_CLIENT_ID; if (!value) throw new Error('Google OAuth client ID is not configured. Set GOOGLE_CLIENT_ID or VITE_GOOGLE_CLIENT_ID.'); return value; }
export function publicDriveApiKey() { return process.env.GOOGLE_API_KEY || process.env.GOOGLE_MAPS_API_KEY || ''; }
function redirectUri() { return process.env.GOOGLE_REDIRECT_URI || `${(process.env.APP_URL || 'http://localhost:3000').replace(/\/$/, '')}/api/auth/google/callback`; }
function base64Url(input: Buffer) { return input.toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, ''); }
function createVerifier() { return base64Url(crypto.randomBytes(48)); }
function challenge(verifier: string) { return base64Url(crypto.createHash('sha256').update(verifier).digest()); }
async function loadTokens(): Promise<StoredTokens | null> { if (cachedTokens) return cachedTokens; try { cachedTokens = JSON.parse(await fs.readFile(TOKEN_FILE, 'utf8')) as StoredTokens; return cachedTokens; } catch { return null; } }
async function saveTokens(tokens: StoredTokens) { cachedTokens = tokens; await fs.mkdir(path.dirname(TOKEN_FILE), { recursive: true }); await fs.writeFile(TOKEN_FILE, JSON.stringify(tokens, null, 2), { encoding: 'utf8', mode: 0o600 }); }
export function getGoogleOAuthStatus() { return { configured: Boolean(process.env.GOOGLE_CLIENT_ID || process.env.VITE_GOOGLE_CLIENT_ID || publicDriveApiKey()), authenticated: Boolean(cachedTokens?.refresh_token || cachedTokens?.access_token), publicDrive: Boolean(publicDriveApiKey()), redirectUri: redirectUri(), scope: DRIVE_SCOPE }; }
export function createGoogleAuthorizationUrl() { const state = crypto.randomBytes(32).toString('hex'); const verifier = createVerifier(); pendingStates.set(state, { expiresAt: Date.now() + 10 * 60 * 1000, verifier }); const params = new URLSearchParams({ client_id: clientId(), redirect_uri: redirectUri(), response_type: 'code', access_type: 'offline', prompt: 'consent', include_granted_scopes: 'true', scope: DRIVE_SCOPE, state, code_challenge: challenge(verifier), code_challenge_method: 'S256' }); return `${GOOGLE_AUTH_URL}?${params.toString()}`; }
export async function exchangeGoogleCode(code: string, state: string) { const pending = pendingStates.get(state); pendingStates.delete(state); if (!pending || pending.expiresAt < Date.now()) throw new Error('Google OAuth state is missing or expired.'); const body = new URLSearchParams({ code, client_id: clientId(), redirect_uri: redirectUri(), grant_type: 'authorization_code', code_verifier: pending.verifier }); const response = await fetch(GOOGLE_TOKEN_URL, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body }); const payload = await response.json() as any; if (!response.ok || !payload.access_token) throw new Error(payload.error_description || payload.error || 'Google OAuth token exchange failed.'); const previous = await loadTokens(); await saveTokens({ access_token: payload.access_token, refresh_token: payload.refresh_token || previous?.refresh_token, expires_at: Date.now() + Number(payload.expires_in || 3600) * 1000, scope: payload.scope, token_type: payload.token_type }); }
export async function getGoogleAccessToken(): Promise<string | null> { const tokens = await loadTokens(); if (!tokens) return null; if (tokens.access_token && tokens.expires_at && tokens.expires_at > Date.now() + 60_000) return tokens.access_token; if (!tokens.refresh_token) return tokens.access_token || null; const body = new URLSearchParams({ client_id: clientId(), refresh_token: tokens.refresh_token, grant_type: 'refresh_token' }); const response = await fetch(GOOGLE_TOKEN_URL, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body }); const payload = await response.json() as any; if (!response.ok || !payload.access_token) { cachedTokens = null; throw new Error(payload.error_description || payload.error || 'Google access-token refresh failed; reconnect Drive.'); } const refreshed = payload.access_token as string; await saveTokens({ ...tokens, access_token: refreshed, expires_at: Date.now() + Number(payload.expires_in || 3600) * 1000, scope: payload.scope || tokens.scope, token_type: payload.token_type || tokens.token_type }); return refreshed; }
export async function revokeGoogleAccess() { const tokens = await loadTokens(); if (tokens?.refresh_token) await fetch(`https://oauth2.googleapis.com/revoke?token=${encodeURIComponent(tokens.refresh_token)}`, { method: 'POST' }); cachedTokens = null; await fs.rm(TOKEN_FILE, { force: true }); }
