#!/usr/bin/env python3
"""Functionally probe installed OSS tools without producing production evidence.

The probe intentionally uses only a tiny synthetic image. A successful probe means
an installed capability executed correctly; it never means a production artifact
passed QC or that a show shot exists.
"""
from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / ".artifacts" / "evidence" / "oss_functional_probe.json"


def run(cmd: list[str], timeout: int = 15) -> dict[str, object]:
    exe = shutil.which(cmd[0])
    if not exe:
        return {"status": "UNAVAILABLE", "command": cmd, "path": None}
    try:
        p = subprocess.run([exe, *cmd[1:]], capture_output=True, text=True, timeout=timeout)
        text = (p.stdout or p.stderr).strip().splitlines()
        return {
            "status": "PASS" if p.returncode == 0 else "FAIL",
            "returncode": p.returncode,
            "path": exe,
            "output": text[:8],
        }
    except (OSError, subprocess.SubprocessError) as exc:
        return {"status": "FAIL", "path": exe, "error": str(exc)}


def main() -> int:
    result: dict[str, object] = {
        "schema": "trippedd.oss-functional-probe/v1",
        "status": "FUNCTIONAL_CAPABILITY_PROBE",
        "evidence_status": "NOT_ATTEMPTED",
        "production_evidence": False,
        "policy": {
            "synthetic_fixture_only": True,
            "capability_pass_is_not_render_pass": True,
            "exact_production_artifact_required": True,
            "visual_qc_not_attempted": True,
            "physical_qc_not_attempted": True,
        },
        "checks": {},
    }

    with tempfile.TemporaryDirectory(prefix="trippedd-oss-probe-") as td:
        root = Path(td)
        # 2x2 RGBA PNG with deliberately simple bytes, generated by stdlib only.
        png = root / "fixture.png"
        import struct
        import zlib
        raw = b"\x00" + b"\xff\x00\x00\xff" * 2 + b"\x00" + b"\x00\xff\x00\xff" * 2
        def chunk(tag: bytes, data: bytes) -> bytes:
            return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xffffffff)
        png.write_bytes(b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", 2, 2, 8, 6, 0, 0, 0)) + chunk(b"IDAT", zlib.compress(raw)) + chunk(b"IEND", b""))
        digest = hashlib.sha256(png.read_bytes()).hexdigest()
        result["fixture"] = {"path": str(png), "sha256": digest, "bytes": png.stat().st_size}

        iinfo = run(["iinfo", str(png)])
        result["checks"]["oiio_iinfo_png"] = iinfo
        result["checks"]["oiio_idiff_self"] = run(["idiff", str(png), str(png)])
        result["checks"]["oiiotool_info_png"] = run(["oiiotool", "--info", str(png)])
        result["checks"]["blender_version"] = run(["blender", "--version"])
        result["checks"]["ffmpeg_version"] = run(["ffmpeg", "-version"])
        result["checks"]["openrv_version"] = run(["rv", "-version"])
        result["checks"]["xstudio_version"] = run(["xstudio", "--version"])
        result["checks"]["cueadmin_version"] = run(["cueadmin", "--version"])

    checks = result["checks"]
    result["summary"] = {
        "functional_passes": sum(1 for v in checks.values() if v.get("status") == "PASS"),
        "functional_failures": sum(1 for v in checks.values() if v.get("status") == "FAIL"),
        "unavailable": sum(1 for v in checks.values() if v.get("status") == "UNAVAILABLE"),
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
