export const LUCK_OF_THE_IRISH_DISCLAIMERS = [
  { id: '001', type: 'CANONICAL_ORIGINAL', text: 'Luck of the Irish is not responsible for luck, Ireland, leprechauns, gold, or any resulting bullshit.' },
  { id: '002', type: 'COMMERCIAL_LINE', text: 'Luck of the Irish™. Nobody knows what it is.' },
  { id: '003', type: 'COMMERCIAL_LINE', text: 'Available wherever absolutely nothing is sold.' },
  { id: '004', type: 'ACTIVE', text: 'Luck of the Irish may cause excessive luck, unexpected misfortune, or an uncontrollable desire to yell at strangers.' },
  { id: '005', type: 'ACTIVE', text: 'Do not operate Luck of the Irish while driving, swimming, gambling, sleeping, or making responsible decisions.' },
  { id: '006', type: 'ACTIVE', text: 'Luck of the Irish is not a substitute for money, common sense, medical advice, or whatever the hell you thought this was.' },
  { id: '007', type: 'ACTIVE', text: 'Side effects may include confusion, confidence, temporary wealth, permanent stupidity, and unexplained green objects.' },
  { id: '008', type: 'ACTIVE', text: 'Luck of the Irish has not been evaluated by anyone qualified to evaluate anything. Results may vary.' },
  { id: '009', type: 'ACTIVE', text: 'If your luck lasts longer than four hours, congratulations. Nobody knows what to do next.' },
  { id: '010', type: 'ACTIVE', text: 'Luck of the Irish does not guarantee Irishness, luckiness, gold, rainbows, pots, leprechauns, or a satisfactory explanation.' },
  { id: '011', type: 'ACTIVE', text: 'Please consult anybody before using Luck of the Irish™.' },
  { id: '012', type: 'ACTIVE', text: 'Luck of the Irish™ may contain traces of luck, Irishness, or absolutely nothing.' },
  { id: '013', type: 'ACTIVE', text: 'Luck of the Irish™. Because apparently somebody had to make this.' },
];
