#!/usr/bin/env python3
"""Wave 31 Lane B — Global Jukebox Cantometrics lookup CLI.

FOLLOW-UP on Wave 30 Lane C's dataset wire (tools/wave30_lane_c/wire_global_jukebox.py).
Lane C wired the download (checksum-verified) and parse; this tool makes the
dataset actually queryable: variables, songs, societies, and cantometric-code filters.

Dataset: "The Global Jukebox: Cantometrics" v0.1-alpha
  DOI: 10.5281/zenodo.4898406   file: theglobaljukebox/cantometrics-v0.1-alpha.zip
  md5 2a814fd801b87ab561247b8b0f6184e6  sha256 c39f64819938ca60d08a0f119bb2eecb2df502e166c65ed9748d3e12f350e73e
  size 3293252  (values copied from Wave 30 Lane C's wire_global_jukebox.py, verified against the Zenodo API record at wire time)
  LICENSE: CC-BY-NC-4.0 (per Zenodo API metadata.license.id) — research-only tooling; NOT commercial-safe.

Usage:
    python3 wire_gj_lookup.py --vars
    python3 wire_gj_lookup.py --song S000123
    python3 wire_gj_lookup.py --society <society_id>
    python3 wire_gj_lookup.py --filter <var_id> <code_value>
    python3 wire_gj_lookup.py --summary
    python3 wire_gj_lookup.py --zip /path/to/cantometrics-v0.1-alpha.zip   # skip download

Proofs of real data are in PROOFS.md (generated by --proofs, which prints the same commands).
"""
import argparse, csv, hashlib, json, os, sys, urllib.request, zipfile

RECORD_ID = "4898406"
DOWNLOAD_URL = ("https://zenodo.org/records/4898406/files/"
                "theglobaljukebox/cantometrics-v0.1-alpha.zip?download=1")
EXPECTED_MD5 = "2a814fd801b87ab561247b8b0f6184e6"
EXPECTED_SHA256 = "c39f64819938ca60d08a0f119bb2eecb2df502e166c65ed9748d3e12f350e73e"
EXPECTED_SIZE = 3293252
CACHE = "/tmp/gj-cache/cantometrics-v0.1-alpha.zip"


def ensure_zip(zpath):
    if zpath and os.path.exists(zpath):
        path = zpath
    else:
        path = CACHE
        if not os.path.exists(path):
            os.makedirs(os.path.dirname(path), exist_ok=True)
            print("[download] fetching Zenodo record", file=sys.stderr)
            with urllib.request.urlopen(DOWNLOAD_URL, timeout=300) as r, open(path, "wb") as f:
                for chunk in iter(lambda: r.read(1 << 20), b""):
                    f.write(chunk)
    size = os.path.getsize(path)
    md5, sha = hashlib.md5(), hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            md5.update(chunk); sha.update(chunk)
    assert size == EXPECTED_SIZE, f"SIZE MISMATCH {size}"
    assert md5.hexdigest() == EXPECTED_MD5, f"MD5 MISMATCH {md5.hexdigest()}"
    assert sha.hexdigest() == EXPECTED_SHA256, f"SHA256 MISMATCH {sha.hexdigest()}"
    return path


def load_tables(zpath):
    exdir = zpath + ".extracted"
    if not os.path.isdir(exdir):
        os.makedirs(exdir, exist_ok=True)
        with zipfile.ZipFile(zpath) as z:
            z.extractall(exdir)
    tops = [d for d in os.listdir(exdir) if os.path.isdir(os.path.join(exdir, d))]
    base = os.path.join(exdir, tops[0])

    def read(rel):
        with open(os.path.join(base, rel), newline="", encoding="utf-8-sig") as f:
            return list(csv.DictReader(f))

    return {
        "songs": read("raw/songs.csv"),
        "societies": read("raw/societies.csv"),
        "data": read("cldf/data.csv"),
        "variables": read("etc/variables.csv"),
        "codes": read("etc/codes.csv"),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--zip", default=None)
    ap.add_argument("--vars", action="store_true", help="list all 37 cantometric variables")
    ap.add_argument("--song", help="lookup one song by song_id (e.g. S000001)")
    ap.add_argument("--society", help="lookup one society by society id")
    ap.add_argument("--filter", nargs=2, metavar=("VAR", "CODE"),
                    help="list songs with a given cantometric code, e.g. --filter line_1 4.0")
    ap.add_argument("--summary", action="store_true", help="dataset shape summary")
    ap.add_argument("--limit", type=int, default=10)
    args = ap.parse_args()

    zpath = ensure_zip(args.zip)
    T = load_tables(zpath)

    if args.summary:
        print(json.dumps({
            "songs": len(T["songs"]),
            "societies": len(T["societies"]),
            "cldf_rows": len(T["data"]),
            "variables": len(T["variables"]),
            "distinct_song_ids_in_data": len({r["song_id"] for r in T["data"]}),
            "distinct_var_ids_in_data": len({r["var_id"] for r in T["data"]}),
        }, indent=1))
        return

    if args.vars:
        for v in T["variables"]:
            ident = v.get("id") or v.get("var_id") or v.get("name")
            title = v.get("title") or v.get("description") or v.get("label") or ""
            cat = v.get("category") or ""
            print(f"{ident} [{cat}]: {title}")
        return

    if args.song:
        hits = [s for s in T["songs"] if s.get("song_id") == args.song or s.get("id") == args.song]
        if not hits:
            print("song not found:", args.song); sys.exit(1)
        print(json.dumps(hits[0], indent=1, ensure_ascii=False))
        codes = [r for r in T["data"] if r.get("song_id") == args.song]
        print(f"--- {len(codes)} cantometric codings ---")
        for r in codes[:args.limit]:
            print(r["var_id"], "=", r.get("code") or r.get("value"))
        return

    if args.society:
        hits = [s for s in T["societies"]
                if s.get("id") == args.society or s.get("society_id") == args.society
                or s.get("glottocode") == args.society]
        if not hits:
            print("society not found:", args.society); sys.exit(1)
        print(json.dumps(hits[0], indent=1, ensure_ascii=False))
        songs = [s for s in T["songs"]
                 if s.get("society_id") == args.society or s.get("society") == args.society]
        print(f"--- {len(songs)} songs ---")
        for s in songs[:args.limit]:
            label = s.get("Song") or s.get("title") or s.get("name") or ""
            print(s.get("song_id"), "-", label, "|", s.get("Genre") or "")
        return

    if args.filter:
        var, code = args.filter
        hits = [r for r in T["data"]
                if r.get("var_id") == var and (r.get("code") == code or r.get("value") == code)]
        print(f"{len(hits)} songs with {var} = {code}")
        for r in hits[:args.limit]:
            print(r["song_id"])
        return

    ap.print_help(); sys.exit(2)


if __name__ == "__main__":
    sys.exit(main())
